package converter

import (
	"cmp"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"text/template"
)

// -----------------------------------------------------------------------------
// Generator
// -----------------------------------------------------------------------------

// GenerateOptions controls what the generator emits.
type GenerateOptions struct {
	PackageName string // Go package name for the generated file
	OutputDir   string // directory to write generated files into
	TypesFile   string // filename for the types file
	BindingFile string // filename for the bindings file
}

// DefaultOptions returns sensible defaults for the generated output.
func DefaultOptions() GenerateOptions {
	return GenerateOptions{
		PackageName: "generated",
		OutputDir:   ".",
		TypesFile:   "types_gen.go",
		BindingFile: "bindings_gen.go",
	}
}

// Generate runs the generator with the given schema and options.
func Generate(schema *Schema, opts GenerateOptions) error {
	if err := os.MkdirAll(opts.OutputDir, 0o755); err != nil {
		return fmt.Errorf("converter: mkdir %s: %w", opts.OutputDir, err)
	}

	if err := generateTypes(schema, opts); err != nil {
		return err
	}
	if err := generateBindings(schema, opts); err != nil {
		return err
	}
	return nil
}

// -----------------------------------------------------------------------------
// Types template
// -----------------------------------------------------------------------------

var typesTemplate = `// Code generated by havok-go converter. DO NOT EDIT.

package {{.PackageName}}

// =============================================================================
// Enums
// =============================================================================
{{range $enum := .Enums}}
type {{$enum.Name}} int32

const ({{range $i, $v := $enum.Values}}
	{{$enum.Name}}_{{$v}} {{if eq $i 0}}{{$enum.Name}} {{end}}= {{$i}}{{end}}
)
{{end}}

// =============================================================================
// Type aliases (HP handles and composite types)
// =============================================================================
{{range .Types}}
// {{.Name}} mirrors HavokPhysics.d.ts  "type {{.Name}} = [...]"
{{- if .IsHandle}}
type {{.Name}} [1]uint64{{else}}
// Tuple elements: {{range .Tuple}}{{.Raw}}, {{end}}
type {{.Name}} struct {
	// TODO: fill in from AllocSizeOf analysis; placeholder i32 fields:
{{- range $i, $_ := .Tuple}}
	Field{{$i}} uint32{{end}}
}{{end}}
{{end}}
`

func generateTypes(schema *Schema, opts GenerateOptions) error {
	type templateData struct {
		PackageName string
		Enums       []EnumDecl
		Types       []TypeAlias
	}

	data := templateData{
		PackageName: opts.PackageName,
		Enums:       schema.Enums,
		Types:       schema.Types,
	}

	tmpl, err := template.New("types").Parse(typesTemplate)
	if err != nil {
		return fmt.Errorf("converter: types template: %w", err)
	}

	f, err := os.Create(filepath.Join(opts.OutputDir, opts.TypesFile))
	if err != nil {
		return fmt.Errorf("converter: create %s: %w", opts.TypesFile, err)
	}
	defer f.Close()
	return tmpl.Execute(f, data)
}

// -----------------------------------------------------------------------------
// Bindings template
// -----------------------------------------------------------------------------

var bindingsTemplate = `// Code generated by havok-go converter. DO NOT EDIT.
//
// Each function wraps a Havok WASM export following the emscripten sret
// calling convention:
//   • Tuple return types  → sret pointer as first arg; WASM returns void.
//   • Scalar return types → WASM returns i32 directly.
//   • Tuple parameters    → passed as i32 pointer to WASM memory.
//   • number parameters   → passed as f64.
//   • boolean parameters  → passed as i32.

package {{.PackageName}}

import (
	"context"
	"encoding/binary"
	"fmt"
	"math"

	"github.com/tetratelabs/wazero/api"
)

// Binding wraps a wazero api.Module and provides typed HP_* methods.
type Binding struct {
	mod    api.Module
	malloc api.Function
	free   api.Function
}

// NewBinding creates a Binding from an already-instantiated wazero Module.
func NewBinding(mod api.Module) (*Binding, error) {
	m := mod.ExportedFunction("malloc")
	f := mod.ExportedFunction("free")
	if m == nil || f == nil {
		return nil, fmt.Errorf("generated: module missing malloc/free")
	}
	return &Binding{mod: mod, malloc: m, free: f}, nil
}

func (b *Binding) alloc(ctx context.Context, size uint32) (uint32, error) {
	res, err := b.malloc.Call(ctx, uint64(size))
	if err != nil {
		return 0, err
	}
	ptr := uint32(res[0])
	if ptr == 0 {
		return 0, fmt.Errorf("generated: malloc(%d) returned NULL", size)
	}
	buf := make([]byte, size)
	if !b.mod.Memory().Write(ptr, buf) {
		b.free.Call(ctx, uint64(ptr))
		return 0, fmt.Errorf("generated: zero fill failed at %d", ptr)
	}
	return ptr, nil
}

func (b *Binding) freePtr(ctx context.Context, ptr uint32) {
	if ptr != 0 {
		b.free.Call(ctx, uint64(ptr))
	}
}

func readI32(mem api.Memory, offset uint32) (int32, error) {
	bs, ok := mem.Read(offset, 4)
	if !ok {
		return 0, fmt.Errorf("generated: readI32 OOB at %d", offset)
	}
	return int32(binary.LittleEndian.Uint32(bs)), nil
}

func readU64(mem api.Memory, offset uint32) (uint64, error) {
	bs, ok := mem.Read(offset, 8)
	if !ok {
		return 0, fmt.Errorf("generated: readU64 OOB at %d", offset)
	}
	return binary.LittleEndian.Uint64(bs), nil
}

func writeF64(mem api.Memory, offset uint32, v float64) bool {
	bs := make([]byte, 8)
	binary.LittleEndian.PutUint64(bs, math.Float64bits(v))
	return mem.Write(offset, bs)
}

func writeU64(mem api.Memory, offset uint32, v uint64) bool {
	bs := make([]byte, 8)
	binary.LittleEndian.PutUint64(bs, v)
	return mem.Write(offset, bs)
}

// =============================================================================
// Generated HP_* bindings
// =============================================================================
{{range .Methods}}
// {{.Name}} wraps HP_* WASM export.
// TypeScript: {{.Name}}({{range $i, $p := .Params}}{{if $i}}, {{end}}{{$p.Name}}: {{$p.TSType.Raw}}{{end}}): {{.ReturnType.Raw}}
func (b *Binding) {{.Name}}(ctx context.Context{{range .Params}}, {{.Name}} {{call $.GoType .TSType}}{{end}}) {{call $.FuncReturn .ReturnType}} {
	{{- call $.FuncBody . }}
}
{{end}}
`

// -----------------------------------------------------------------------------
// Template helpers
// -----------------------------------------------------------------------------

// templateFuncs provides custom template functions.
type templateFuncs struct {
	schema *Schema
}

func (tf templateFuncs) GoType(t TSType) string    { return tf.schema.GoType(t) }
func (tf templateFuncs) IsTuple(t TSType) bool     { return tf.schema.IsTuple(t) }
func (tf templateFuncs) AllocSize(t TSType) uint32 { return tf.schema.AllocSizeOf(t) }
func (tf templateFuncs) WasmParam(t TSType) string { return tf.schema.WasmParamType(t) }

// FuncReturn builds the Go return type list as a string "(T1, T2, error)".
// For tuple return types (e.g. [Result, HP_BodyId]), it generates multiple return values.
func (tf templateFuncs) FuncReturn(ret TSType) string {
	if ret.Kind == KindVoid || ret.Raw == "" {
		return "error"
	}
	if len(ret.Elements) > 0 {
		// Tuple return: emit each element as a separate return value
		var parts []string
		for _, el := range ret.Elements {
			gt := tf.schema.GoType(el)
			if gt == "" {
				gt = "interface{}"
			}
			parts = append(parts, gt)
		}
		parts = append(parts, "error")
		return "(" + strings.Join(parts, ", ") + ")"
	}
	gt := tf.schema.GoType(ret)
	if gt == "" {
		return "error"
	}
	return fmt.Sprintf("(%s, error)", gt)
}

// FuncBody generates the function body for a given method.
func (tf templateFuncs) FuncBody(m Method) string {
	var b strings.Builder
	isTupleReturn := tf.schema.IsTuple(m.ReturnType)
	retGoType := tf.schema.GoType(m.ReturnType)

	zeroRetExpr := tf.zeroExpr(m.ReturnType)

	retSize := tf.schema.AllocSizeOf(m.ReturnType)
	var wasmArgs []string

	if isTupleReturn {
		b.WriteString(fmt.Sprintf("\n\tsretPtr, err := b.alloc(ctx, %d)\n\tif err != nil { return %s, err }\n\tdefer b.freePtr(ctx, sretPtr)\n",
			retSize, zeroRetExpr))
		wasmArgs = append(wasmArgs, "uint64(sretPtr)")
	}

	for i, p := range m.Params {
		paramVarName := p.Name
		switch p.TSType.Kind {
		case KindNumber:
			wasmArgs = append(wasmArgs, fmt.Sprintf("api.EncodeF64(%s)", paramVarName))
		case KindBoolean:
			boolVar := fmt.Sprintf("_%sBool", paramVarName)
			b.WriteString(fmt.Sprintf("\n\tvar %s uint64\n\tif %s { %s = 1 }\n", boolVar, paramVarName, boolVar))
			wasmArgs = append(wasmArgs, boolVar)
		case KindEnum:
			wasmArgs = append(wasmArgs, fmt.Sprintf("uint64(%s)", paramVarName))
		default:
			// Tuple / handle → write to WASM memory, pass pointer
			ptrName := fmt.Sprintf("_param%dPtr", i)
			pSize := tf.schema.AllocSizeOf(p.TSType)
			b.WriteString(fmt.Sprintf("\n\t%s, err := b.alloc(ctx, %d)\n\tif err != nil { return %s, err }\n\tdefer b.freePtr(ctx, %s)\n",
				ptrName, pSize, zeroRetExpr, ptrName))
			b.WriteString(fmt.Sprintf("\t// TODO: marshal %s into %s (type: %s)\n", paramVarName, ptrName, p.TSType.Raw))
			wasmArgs = append(wasmArgs, fmt.Sprintf("uint64(%s)", ptrName))
		}
	}

	// Call the WASM function
	b.WriteString(fmt.Sprintf("\n\tfn := b.mod.ExportedFunction(%q)\n\tif fn == nil { return %s, fmt.Errorf(%q) }\n",
		m.Name, zeroRetExpr, "generated: "+m.Name+" not exported"))

	if isTupleReturn || m.ReturnType.Kind == KindVoid || retGoType == "" {
		b.WriteString(fmt.Sprintf("\n\tif _, callErr := fn.Call(ctx, %s); callErr != nil { return %s, callErr }\n",
			strings.Join(wasmArgs, ", "), zeroRetExpr))
	} else {
		b.WriteString(fmt.Sprintf("\n\t_res, callErr := fn.Call(ctx, %s)\n\tif callErr != nil { return %s, callErr }\n",
			strings.Join(wasmArgs, ", "), zeroRetExpr))
	}

	// Return result
	if isTupleReturn {
		b.WriteString(fmt.Sprintf("\n\t// TODO: deserialize result from sretPtr (size=%d bytes)\n", retSize))
		b.WriteString(fmt.Sprintf("\treturn %s, nil // placeholder – implement deserialize\n", zeroRetExpr))
	} else if m.ReturnType.Kind == KindVoid || retGoType == "" {
		b.WriteString("\n\treturn nil\n")
	} else {
		// scalar i32 → direct WASM return
		b.WriteString(fmt.Sprintf("\n\treturn %s(int32(_res[0])), nil\n", retGoType))
	}

	return b.String()
}

// zeroExpr returns the Go source for the zero value of t.
// For tuple types it returns a comma-separated list (one zero per element).
func (tf templateFuncs) zeroExpr(t TSType) string {
	if len(t.Elements) > 0 {
		var parts []string
		for _, el := range t.Elements {
			parts = append(parts, tf.scalarZero(el))
		}
		return strings.Join(parts, ", ")
	}
	return tf.scalarZero(t)
}

// scalarZero returns the zero expression for a single (non-tuple) type.
func (tf templateFuncs) scalarZero(t TSType) string {
	switch t.Kind {
	case KindVoid:
		return ""
	case KindNumber:
		return "0"
	case KindBigInt:
		return "0"
	case KindBoolean:
		return "false"
	case KindEnum:
		return "0"
	case KindTupleAlias:
		gt := tf.schema.GoType(t)
		if gt == "" || gt == "interface{}" {
			return "nil"
		}
		return gt + "{}"
	}
	return "nil"
}

func generateBindings(schema *Schema, opts GenerateOptions) error {
	// Sort methods by name for reproducible output
	methods := make([]Method, len(schema.Methods))
	copy(methods, schema.Methods)
	slices.SortFunc(methods, func(a, b Method) int {
		return cmp.Compare(a.Name, b.Name)
	})

	tf := templateFuncs{schema: schema}

	funcMap := template.FuncMap{
		"GoType":     tf.GoType,
		"FuncReturn": tf.FuncReturn,
		"FuncBody":   tf.FuncBody,
	}

	type templateData struct {
		PackageName string
		Methods     []Method
		GoType      func(TSType) string
		FuncReturn  func(TSType) string
		FuncBody    func(Method) string
	}

	data := templateData{
		PackageName: opts.PackageName,
		Methods:     methods,
		GoType:      tf.GoType,
		FuncReturn:  tf.FuncReturn,
		FuncBody:    tf.FuncBody,
	}

	tmpl, err := template.New("bindings").Funcs(funcMap).Parse(bindingsTemplate)
	if err != nil {
		return fmt.Errorf("converter: bindings template: %w", err)
	}

	f, err := os.Create(filepath.Join(opts.OutputDir, opts.BindingFile))
	if err != nil {
		return fmt.Errorf("converter: create %s: %w", opts.BindingFile, err)
	}
	defer f.Close()
	return tmpl.Execute(f, data)
}
