package converter

import (
	"cmp"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"text/template"
)

// -----------------------------------------------------------------------------
// Generator
// -----------------------------------------------------------------------------

// GenerateOptions controls what the generator emits.
type GenerateOptions struct {
	PackageName  string // Go package name for the generated file
	OutputDir    string // directory to write generated files into
	TypesFile    string // filename for the types file (empty = skip)
	BindingFile  string // filename for the bindings file
	SkipTypes    bool   // do not generate types_gen.go (types already defined)
	ReceiverType string // Go type used as method receiver (typically "HP")
	BindingPkg   string // import path of the hand-written binding package
}

// DefaultOptions targets the havok/generated sub-package.
// Types live in havok/binding; generated code wraps binding.Binding via the HP type.
func DefaultOptions() GenerateOptions {
	return GenerateOptions{
		PackageName:  "generated",
		OutputDir:    "./havok/generated",
		TypesFile:    "types_gen.go",
		BindingFile:  "bindings_gen.go",
		SkipTypes:    true,
		ReceiverType: "HP",
		BindingPkg:   "github.com/gsw945/havok-go/havok/binding",
	}
}

// Generate runs the generator with the given schema and options.
func Generate(schema *Schema, opts GenerateOptions) error {
	if err := os.MkdirAll(opts.OutputDir, 0o755); err != nil {
		return fmt.Errorf("converter: mkdir %s: %w", opts.OutputDir, err)
	}

	if !opts.SkipTypes && opts.TypesFile != "" {
		if err := generateTypes(schema, opts); err != nil {
			return err
		}
	}
	if err := generateBindings(schema, opts); err != nil {
		return err
	}
	return nil
}

// -----------------------------------------------------------------------------
// Types template
// -----------------------------------------------------------------------------

var typesTemplate = `// Code generated by havok-go converter. DO NOT EDIT.

package {{.PackageName}}

// =============================================================================
// Enums
// =============================================================================
{{range $enum := .Enums}}
type {{$enum.Name}} int32

const ({{range $i, $v := $enum.Values}}
	{{$enum.Name}}_{{$v}} {{if eq $i 0}}{{$enum.Name}} {{end}}= {{$i}}{{end}}
)
{{end}}

// =============================================================================
// Type aliases (HP handles and composite types)
// =============================================================================
{{range .Types}}
// {{.Name}} mirrors HavokPhysics.d.ts  "type {{.Name}} = [...]"
{{- if .IsHandle}}
type {{.Name}} [1]uint64{{else}}
// Tuple elements: {{range .Tuple}}{{.Raw}}, {{end}}
type {{.Name}} struct {
	// TODO: fill in from AllocSizeOf analysis; placeholder i32 fields:
{{- range $i, $_ := .Tuple}}
	Field{{$i}} uint32{{end}}
}{{end}}
{{end}}
`

func generateTypes(schema *Schema, opts GenerateOptions) error {
	type templateData struct {
		PackageName string
		Enums       []EnumDecl
		Types       []TypeAlias
	}

	data := templateData{
		PackageName: opts.PackageName,
		Enums:       schema.Enums,
		Types:       schema.Types,
	}

	tmpl, err := template.New("types").Parse(typesTemplate)
	if err != nil {
		return fmt.Errorf("converter: types template: %w", err)
	}

	f, err := os.Create(filepath.Join(opts.OutputDir, opts.TypesFile))
	if err != nil {
		return fmt.Errorf("converter: create %s: %w", opts.TypesFile, err)
	}
	defer f.Close()
	return tmpl.Execute(f, data)
}

// -----------------------------------------------------------------------------
// Bindings template
// -----------------------------------------------------------------------------

var bindingsTemplate = `// Code generated by havok-go converter. DO NOT EDIT.
//
// Calling conventions (emscripten embind, Havok WASM):
//   • [Result, HP_*Id] returns → sret(8 bytes) goes LAST; WASM returns Result as i32.
//   • [Result, data]   returns → sret(4+N bytes) goes FIRST; WASM returns void.
//   • Scalar Result    returns → WASM returns i32 directly (uses CallResultI32).
//   • HP_*Id params    → passed directly as uint64 (not via pointer).
//   • number params    → api.EncodeF32(float32(v)) – Havok uses f32 internally.
//   • boolean params   → conditional uint64.

package {{.PackageName}}

import (
	"context"
	"fmt"

	"{{.BindingPkg}}"
	"github.com/tetratelabs/wazero/api"
)

// HP wraps a *binding.Binding and provides all generated HP_* methods.
type HP struct{ *binding.Binding }

// NewHP wraps a *binding.Binding to provide all HP_* methods.
func NewHP(b *binding.Binding) *HP { return &HP{b} }

// =============================================================================
// Generated HP_* bindings (methods on *HP)
// =============================================================================
{{range .Methods}}
// TypeScript: {{.Name}}({{range $i, $p := .Params}}{{if $i}}, {{end}}{{$p.Name}}: {{$p.TSType.Raw}}{{end}}): {{.ReturnType.Raw}}
func (h *{{$.ReceiverType}}) {{.Name}}(ctx context.Context{{range .Params}}, {{.Name}} {{call $.QualifiedGoType .TSType}}{{end}}) {{call $.FuncReturn .ReturnType}} {
{{- call $.FuncBody . }}
}
{{end}}
`

// -----------------------------------------------------------------------------
// Template helpers
// -----------------------------------------------------------------------------

// templateFuncs provides custom template functions.
type templateFuncs struct {
	schema     *Schema
	typePrefix string // e.g. "binding." — prepended to non-primitive type names in generated code
}

func (tf templateFuncs) GoType(t TSType) string { return tf.schema.GoType(t) }

// QualifiedGoType returns the Go type name with the binding package prefix for
// non-primitive types (enums, handles, composites). Pass this wherever generated
// code lives in a different package than the type definitions.
func (tf templateFuncs) QualifiedGoType(t TSType) string {
	bare := tf.schema.GoType(t)
	if tf.typePrefix == "" {
		return bare
	}
	switch t.Kind {
	case KindVoid, KindNumber, KindBigInt, KindBoolean:
		return bare
	default:
		if bare == "" || bare == "interface{}" {
			return bare
		}
		return tf.typePrefix + bare
	}
}
func (tf templateFuncs) IsTuple(t TSType) bool     { return tf.schema.IsTuple(t) }
func (tf templateFuncs) AllocSize(t TSType) uint32 { return tf.schema.AllocSizeOf(t) }
func (tf templateFuncs) WasmParam(t TSType) string { return tf.schema.WasmParamType(t) }

// FuncReturn builds the Go return type list as a string "(T1, T2, error)".
// For tuple return types (e.g. [Result, HP_BodyId]), it generates multiple return values.
func (tf templateFuncs) FuncReturn(ret TSType) string {
	if ret.Kind == KindVoid || ret.Raw == "" {
		return "error"
	}
	if len(ret.Elements) > 0 {
		// Tuple return: emit each element as a separate return value
		var parts []string
		for _, el := range ret.Elements {
			gt := tf.QualifiedGoType(el)
			if gt == "" {
				gt = "interface{}"
			}
			parts = append(parts, gt)
		}
		parts = append(parts, "error")
		return "(" + strings.Join(parts, ", ") + ")"
	}
	gt := tf.QualifiedGoType(ret)
	if gt == "" {
		return "error"
	}
	return fmt.Sprintf("(%s, error)", gt)
}

// isHandleType returns true if t is an HP_*Id handle type (single i64).
func (tf templateFuncs) isHandleType(t TSType) bool {
	if t.Kind != KindTupleAlias {
		return false
	}
	// Check typeMap first.
	if alias, ok := tf.schema.typeMap[t.Raw]; ok {
		return alias.IsHandle
	}
	// Fallback: use HP_*Id naming convention (e.g. HP_BodyId, HP_WorldId).
	return strings.HasPrefix(t.Raw, "HP_") && strings.HasSuffix(t.Raw, "Id")
}

// isHandleReturn returns true if the method returns [Result, HP_*Id].
func (tf templateFuncs) isHandleReturn(ret TSType) bool {
	if len(ret.Elements) != 2 {
		return false
	}
	return tf.isHandleType(ret.Elements[1])
}

// marshalParam returns setup code and the WASM argument expression for one parameter.
// Setup code (if non-empty) is emitted before fn.Call.
func (tf templateFuncs) marshalParam(name string, idx int, t TSType, zeroRet string) (setup string, wasmArg string) {
	switch t.Kind {
	case KindNumber:
		return "", fmt.Sprintf("api.EncodeF32(float32(%s))", name)
	case KindBoolean:
		bv := fmt.Sprintf("_p%dB", idx)
		s := fmt.Sprintf("\n\tvar %s uint64\n\tif %s { %s = 1 }", bv, name, bv)
		return s, bv
	case KindEnum:
		return "", fmt.Sprintf("uint64(%s)", name)
	case KindTupleAlias:
		if tf.isHandleType(t) {
			// Handle: pass the i64 value directly.
			return "", fmt.Sprintf("%s[0]", name)
		}
		// Non-handle tuple: allocate WASM memory, write value, pass pointer.
		ptr := fmt.Sprintf("_p%dPtr", idx)
		writeCode, sz, known := tf.tupleWriteCode(name, ptr, zeroRet, t)
		if !known {
			sz = tf.schema.AllocSizeOf(t)
			writeCode = fmt.Sprintf("\t// TODO: marshal %s (%s) into %s\n", name, t.Raw, ptr)
		}
		s := fmt.Sprintf(
			"\n\t%s, err := h.Alloc(ctx, %d)\n\tif err != nil { return %s, err }\n\tdefer h.FreePtr(ctx, %s)\n%s",
			ptr, sz, zeroRet, ptr, writeCode)
		return s, fmt.Sprintf("uint64(%s)", ptr)
	}
	return "", "0 /* unknown */"
}

// tupleWriteCode generates the write code, WASM size, and "known" flag for a tuple param.
func (tf templateFuncs) tupleWriteCode(varName, ptrName, zeroRet string, t TSType) (code string, size uint32, ok bool) {
	switch t.Raw {
	case "Vector3":
		c := fmt.Sprintf("\tif err := binding.WriteVector3(h.Mem(), %s, %s); err != nil { return %s, err }\n", ptrName, varName, zeroRet)
		return c, 12, true
	case "Quaternion":
		c := fmt.Sprintf("\tif err := binding.WriteQuaternion(h.Mem(), %s, %s); err != nil { return %s, err }\n", ptrName, varName, zeroRet)
		return c, 16, true
	case "QTransform":
		c := fmt.Sprintf(
			"\tif err := binding.WriteVector3(h.Mem(), %s, %s.Translation); err != nil { return %s, err }\n"+
				"\tif err := binding.WriteQuaternion(h.Mem(), %s+12, %s.Rotation); err != nil { return %s, err }\n",
			ptrName, varName, zeroRet, ptrName, varName, zeroRet)
		return c, 28, true
	case "FilterInfo":
		c := fmt.Sprintf(
			"\tif err := binding.WriteU32(h.Mem(), %s, %s.MembershipMask); err != nil { return %s, err }\n"+
				"\tif err := binding.WriteU32(h.Mem(), %s+4, %s.CollisionMask); err != nil { return %s, err }\n",
			ptrName, varName, zeroRet, ptrName, varName, zeroRet)
		return c, 8, true
	}
	return "", 0, false
}

// sretUnmarshal generates the Go code to read the data element from sret at the given
// byte offset, plus returns the element's WASM byte size and a "known" flag.
func (tf templateFuncs) sretUnmarshal(elem TSType, offset uint32, zeroRet string) (code string, size uint32, ok bool) {
	switch elem.Raw {
	case "Vector3":
		c := fmt.Sprintf("\t_data, err := binding.ReadVector3(h.Mem(), sretPtr+%d)\n\tif err != nil { return %s, err }", offset, zeroRet)
		return c, 12, true
	case "Quaternion":
		c := fmt.Sprintf("\t_data, err := binding.ReadQuaternion(h.Mem(), sretPtr+%d)\n\tif err != nil { return %s, err }", offset, zeroRet)
		return c, 16, true
	case "QTransform":
		c := fmt.Sprintf(
			"\t_dTrans, err := binding.ReadVector3(h.Mem(), sretPtr+%d)\n\tif err != nil { return %s, err }\n"+
				"\t_dRot, err2 := binding.ReadQuaternion(h.Mem(), sretPtr+%d)\n\tif err2 != nil { return %s, err2 }\n"+
				"\t_data := binding.QTransform{Translation: _dTrans, Rotation: _dRot}",
			offset, zeroRet, offset+12, zeroRet)
		return c, 28, true
	case "FilterInfo":
		c := fmt.Sprintf(
			"\t_m1, err := binding.ReadU32(h.Mem(), sretPtr+%d)\n\tif err != nil { return %s, err }\n"+
				"\t_m2, err2 := binding.ReadU32(h.Mem(), sretPtr+%d)\n\tif err2 != nil { return %s, err2 }\n"+
				"\t_data := binding.FilterInfo{MembershipMask: _m1, CollisionMask: _m2}",
			offset, zeroRet, offset+4, zeroRet)
		return c, 8, true
	case "ObjectStatistics":
		lines := []string{
			fmt.Sprintf("\t_s0, err := binding.ReadI32(h.Mem(), sretPtr+%d); if err != nil { return %s, err }", offset+0, zeroRet),
			fmt.Sprintf("\t_s1, err1 := binding.ReadI32(h.Mem(), sretPtr+%d); if err1 != nil { return %s, err1 }", offset+4, zeroRet),
			fmt.Sprintf("\t_s2, err2 := binding.ReadI32(h.Mem(), sretPtr+%d); if err2 != nil { return %s, err2 }", offset+8, zeroRet),
			fmt.Sprintf("\t_s3, err3 := binding.ReadI32(h.Mem(), sretPtr+%d); if err3 != nil { return %s, err3 }", offset+12, zeroRet),
			fmt.Sprintf("\t_s4, err4 := binding.ReadI32(h.Mem(), sretPtr+%d); if err4 != nil { return %s, err4 }", offset+16, zeroRet),
			fmt.Sprintf("\t_s5, err5 := binding.ReadI32(h.Mem(), sretPtr+%d); if err5 != nil { return %s, err5 }", offset+20, zeroRet),
			"\t_data := binding.ObjectStatistics{NumBodies: _s0, NumShapes: _s1, NumConstraints: _s2, NumDebugGeometries: _s3, NumWorlds: _s4, NumQueryCollectors: _s5}",
		}
		return strings.Join(lines, "\n"), 24, true
	}
	switch elem.Kind {
	case KindNumber:
		c := fmt.Sprintf(
			"\t_raw, err := binding.ReadF32(h.Mem(), sretPtr+%d)\n\tif err != nil { return %s, err }\n\t_data := float64(_raw)",
			offset, zeroRet)
		return c, 4, true
	case KindEnum:
		c := fmt.Sprintf(
			"\t_raw, err := binding.ReadI32(h.Mem(), sretPtr+%d)\n\tif err != nil { return %s, err }\n\t_data := binding.%s(_raw)",
			offset, zeroRet, elem.Raw)
		return c, 4, true
	case KindBoolean:
		c := fmt.Sprintf(
			"\t_raw, err := binding.ReadI32(h.Mem(), sretPtr+%d)\n\tif err != nil { return %s, err }\n\t_data := _raw != 0",
			offset, zeroRet)
		return c, 4, true
	}
	return "", 0, false
}

// FuncBody generates the complete function body for a given method.
//
// Conventions implemented:
//   - Scalar Result return → h.callResultI32(ctx, name, args...)
//   - [Result, HP_*Id] return (Convention A) → sret(8) LAST, Result as i32 return
//   - [Result, data] return (Convention B) → sret(4+size) FIRST, WASM returns void
func (tf templateFuncs) FuncBody(m Method) string {
	var b strings.Builder

	zeroRet := tf.zeroExpr(m.ReturnType)
	isTuple := tf.schema.IsTuple(m.ReturnType)
	isHandleRet := isTuple && tf.isHandleReturn(m.ReturnType)

	var wasmArgs []string

	// Step 1: allocate sret buffer for tuple-returning functions.
	if isTuple {
		if isHandleRet {
			// Convention A: sret(8) holds the i64 handle; sret goes LAST after inputs.
			b.WriteString(fmt.Sprintf("\n\tsretPtr, err := h.Alloc(ctx, 8)\n\tif err != nil { return %s, err }\n\tdefer h.FreePtr(ctx, sretPtr)", zeroRet))
		} else {
			// Convention B: sret = [Result(4), data]; sret goes FIRST.
			sretSize := uint32(4)
			if len(m.ReturnType.Elements) >= 2 {
				_, ds, _ := tf.sretUnmarshal(m.ReturnType.Elements[1], 4, zeroRet)
				if ds == 0 {
					ds = tf.schema.AllocSizeOf(m.ReturnType.Elements[1])
				}
				sretSize += ds
			} else {
				total := tf.schema.AllocSizeOf(m.ReturnType)
				if total > 4 {
					sretSize = total
				}
			}
			b.WriteString(fmt.Sprintf("\n\tsretPtr, err := h.Alloc(ctx, %d)\n\tif err != nil { return %s, err }\n\tdefer h.FreePtr(ctx, sretPtr)", sretSize, zeroRet))
			wasmArgs = append(wasmArgs, "uint64(sretPtr)") // sret goes FIRST
		}
	}

	// Step 2: marshal each input parameter.
	for i, p := range m.Params {
		setup, arg := tf.marshalParam(p.Name, i, p.TSType, zeroRet)
		if setup != "" {
			b.WriteString(setup)
		}
		wasmArgs = append(wasmArgs, arg)
	}

	// Convention A: sret goes LAST.
	if isTuple && isHandleRet {
		wasmArgs = append(wasmArgs, "uint64(sretPtr)")
	}

	argsStr := ""
	if len(wasmArgs) > 0 {
		argsStr = ", " + strings.Join(wasmArgs, ", ")
	}

	// Step 3: call the WASM function.
	if !isTuple {
		if m.ReturnType.Kind == KindEnum || m.ReturnType.Kind == KindVoid || m.ReturnType.Raw == "" {
			// Enum / Result / void: delegate to CallResultI32 helper.
			b.WriteString(fmt.Sprintf("\n\treturn h.CallResultI32(ctx, %q%s)", m.Name, argsStr))
		} else {
			// number / bool: call fn directly and decode the raw WASM return.
			b.WriteString(fmt.Sprintf("\n\tfn := h.Module().ExportedFunction(%q)", m.Name))
			b.WriteString(fmt.Sprintf("\n\tif fn == nil { return %s, fmt.Errorf(\"havok: %%s not exported\", %q) }", zeroRet, m.Name))
			b.WriteString(fmt.Sprintf("\n\t_res, callErr := fn.Call(ctx%s)\n\tif callErr != nil { return %s, fmt.Errorf(\"havok: %%s: %%w\", %q, callErr) }", argsStr, zeroRet, m.Name))
			switch m.ReturnType.Kind {
			case KindNumber:
				// number return = raw i32/u32 (WASM pointer or count), cast to float64.
				b.WriteString("\n\treturn float64(uint32(_res[0])), nil")
			case KindBoolean:
				b.WriteString("\n\treturn _res[0] != 0, nil")
			default:
				b.WriteString(fmt.Sprintf("\n\treturn %s, nil", zeroRet))
			}
		}
	} else if isHandleRet {
		// Convention A: WASM returns i32 (Result) directly.
		b.WriteString(fmt.Sprintf("\n\tfn := h.Module().ExportedFunction(%q)", m.Name))
		b.WriteString(fmt.Sprintf("\n\tif fn == nil { return %s, fmt.Errorf(\"havok: %%s not exported\", %q) }", zeroRet, m.Name))
		b.WriteString(fmt.Sprintf("\n\t_res, callErr := fn.Call(ctx%s)\n\tif callErr != nil { return %s, fmt.Errorf(\"havok: %%s: %%w\", %q, callErr) }", argsStr, zeroRet, m.Name))
	} else {
		// Convention B: WASM returns void; everything in sret.
		b.WriteString(fmt.Sprintf("\n\tfn := h.Module().ExportedFunction(%q)", m.Name))
		b.WriteString(fmt.Sprintf("\n\tif fn == nil { return %s, fmt.Errorf(\"havok: %%s not exported\", %q) }", zeroRet, m.Name))
		b.WriteString(fmt.Sprintf("\n\tif _, callErr := fn.Call(ctx%s); callErr != nil { return %s, fmt.Errorf(\"havok: %%s: %%w\", %q, callErr) }", argsStr, zeroRet, m.Name))
	}

	// Step 4: deserialize return value.
	if isTuple {
		if isHandleRet && len(m.ReturnType.Elements) >= 2 {
			// Convention A: handle in sret[0..7], Result from WASM return.
			handleType := m.ReturnType.Elements[1].Raw
			b.WriteString(fmt.Sprintf("\n\t_handle, err := binding.ReadU64(h.Mem(), sretPtr)\n\tif err != nil { return %s, err }", zeroRet))
			b.WriteString(fmt.Sprintf("\n\treturn binding.Result(int32(_res[0])), binding.%s{_handle}, nil", handleType))
		} else if len(m.ReturnType.Elements) >= 2 {
			// Convention B: Result at sret[0], data at sret[4].
			dataElem := m.ReturnType.Elements[1]
			b.WriteString(fmt.Sprintf("\n\t_result, err := binding.ReadI32(h.Mem(), sretPtr)\n\tif err != nil { return %s, err }", zeroRet))
			unmCode, _, known := tf.sretUnmarshal(dataElem, 4, zeroRet)
			if known && len(m.ReturnType.Elements) == 2 {
				// Two-element tuple [Result, T]: fully implement.
				b.WriteString("\n" + unmCode)
				b.WriteString(fmt.Sprintf("\n\treturn %sResult(_result), _data, nil", tf.typePrefix))
			} else {
				// Multi-element tuple or unknown type: generate TODO stub.
				b.WriteString(fmt.Sprintf("\n\t_ = _result\n\t// TODO: deserialize tuple from sret\n\treturn %s, nil", zeroRet))
			}
		}
	}

	return b.String()
}

// zeroExpr returns the Go source for the zero value of t.
// For tuple types it returns a comma-separated list (one zero per element).
func (tf templateFuncs) zeroExpr(t TSType) string {
	if len(t.Elements) > 0 {
		var parts []string
		for _, el := range t.Elements {
			parts = append(parts, tf.scalarZero(el))
		}
		return strings.Join(parts, ", ")
	}
	return tf.scalarZero(t)
}

// scalarZero returns the zero expression for a single (non-tuple) type.
func (tf templateFuncs) scalarZero(t TSType) string {
	switch t.Kind {
	case KindVoid:
		return ""
	case KindNumber:
		return "0"
	case KindBigInt:
		return "0"
	case KindBoolean:
		return "false"
	case KindEnum:
		return "0"
	case KindTupleAlias:
		gt := tf.QualifiedGoType(t)
		if gt == "" || gt == "interface{}" {
			return "nil"
		}
		return gt + "{}"
	}
	return "nil"
}

func generateBindings(schema *Schema, opts GenerateOptions) error {
	// Sort methods by name for reproducible output
	methods := make([]Method, len(schema.Methods))
	copy(methods, schema.Methods)
	slices.SortFunc(methods, func(a, b Method) int {
		return cmp.Compare(a.Name, b.Name)
	})

	receiverType := opts.ReceiverType
	if receiverType == "" {
		receiverType = "HP"
	}

	bindingPkg := opts.BindingPkg
	if bindingPkg == "" {
		bindingPkg = "github.com/gsw945/havok-go/havok/binding"
	}

	// Derive the package alias from the last segment of the import path (e.g. "binding").
	typePrefix := ""
	if bindingPkg != "" {
		parts := strings.Split(bindingPkg, "/")
		typePrefix = parts[len(parts)-1] + "."
	}
	tf := templateFuncs{schema: schema, typePrefix: typePrefix}

	funcMap := template.FuncMap{
		"GoType":          tf.GoType,
		"QualifiedGoType": tf.QualifiedGoType,
		"FuncReturn":      tf.FuncReturn,
		"FuncBody":        tf.FuncBody,
	}

	type templateData struct {
		PackageName     string
		ReceiverType    string
		BindingPkg      string
		Methods         []Method
		GoType          func(TSType) string
		QualifiedGoType func(TSType) string
		FuncReturn      func(TSType) string
		FuncBody        func(Method) string
	}

	data := templateData{
		PackageName:     opts.PackageName,
		ReceiverType:    receiverType,
		BindingPkg:      bindingPkg,
		Methods:         methods,
		GoType:          tf.GoType,
		QualifiedGoType: tf.QualifiedGoType,
		FuncReturn:      tf.FuncReturn,
		FuncBody:        tf.FuncBody,
	}

	tmpl, err := template.New("bindings").Funcs(funcMap).Parse(bindingsTemplate)
	if err != nil {
		return fmt.Errorf("converter: bindings template: %w", err)
	}

	f, err := os.Create(filepath.Join(opts.OutputDir, opts.BindingFile))
	if err != nil {
		return fmt.Errorf("converter: create %s: %w", opts.BindingFile, err)
	}
	defer f.Close()
	return tmpl.Execute(f, data)
}
